<!-- Trabalho Desenvolvido na Data Science Academy - www.datascienceacademy.com.br -->
# <font color='blue'>Data Science Academy</font>
# <font color='blue'>Fundamentos de Linguagem Python - Do Básico a Aplicações de IA</font>
# <font color='blue'>Lista 3 de Exercícios</font>

Classificamos os 10 exercícios nas seguintes categorias:

- (Nível Baby)
- (Nível Aprendiz)
- (Nível Iniciante)
- (Nível Iniciante Plus)
- (Nível Pro)
- (Nível Master)
- (Nível Ninja)
- (Nível Ninja Pro Master)
- (Nível Ninja Pro Master das Galáxias)
- (Nível Ninja Pro Master das Galáxias Plus)

Divirta-se. :-)

In [1]:
# Importa o NumPy
import numpy as np

#### Exercício 1: Selecionando uma Coluna Específica (Nível Baby)

Dado a matriz 4x4 abaixo, crie um novo array contendo apenas os elementos da terceira coluna.

In [2]:
# Cria a matriz
matriz = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
    [13, 14, 15, 16]
])

In [4]:
# Solução
novo_array = matriz[:, 2]
print(novo_array)

# Saída esperada: [ 3  7 11 15]

[ 3  7 11 15]


#### Exercício 2: Extraindo um Bloco (Submatriz) (Nível Aprendiz)

A partir da mesma matriz do exercício 1, extraia o bloco central 2x2, que contém os números 6, 7, 10 e 11.

In [7]:
# Solução
bloco_central = matriz[1:3, 1:3]
print(bloco_central)

# Saída esperada:
# [[ 6  7]
#  [10 11]]

[[ 6  7]
 [10 11]]


#### Exercício 3: Produto de Matrizes (Nível Iniciante)

Dadas as duas matrizes A e B abaixo, calcule o produto matricial entre A e B.

In [ ]:
# Cria as matrizes
A = np.array([[1, 2, 3], [4, 5, 6]])       # Matriz 2x3
B = np.array([[7, 8], [9, 10], [11, 12]])  # Matriz 3x2

In [19]:
# Solução
A = np.array([[1, 2, 3], [4, 5, 6]])       # Matriz 2x3
B = np.array([[7, 8], [9, 10], [11, 12]])  # Matriz 3x2

resultado_arroba = A @ B
resultado_dot = np.dot(A, B)
resultado_mult = np.matmul(A, B)
# resultado_vezes = A * B só é possível se o número de linhas e colunas forem iguais

print(f"Resultado Usando @:\n{resultado_arroba}\n")
print(f"Resultado Usando Dot:\n{resultado_dot}\n")
print(f"Resultado Usando matmul: \n{resultado_mult}")
# print(f"Resultado Usando Estrela:\n{resultado_vezes}")


# Saída esperada:
# [[ 58  64]
#  [139 154]]

Resultado Usando @:
[[ 58  64]
 [139 154]]

Resultado Usando Dot:
[[ 58  64]
 [139 154]]

Resultado Usando matmul: 
[[ 58  64]
 [139 154]]


#### Exercício 4: Selecionando Linhas Pares e Colunas Ímpares (Nível Iniciante Plus)

Dada a matriz 9x9 abaixo, crie um novo array que contenha apenas os valores das linhas de índice par e as colunas de índice ímpar.

In [ ]:
# Cria a matriz
matriz = np.arange(81).reshape(9, 9)

In [21]:
# Solução
# Cria a matriz
matriz = np.arange(81).reshape(9, 9)
array_row_par_column_impar = matriz[::2, 1::2]

print(array_row_par_column_impar)

# Saída esperada:
# [[ 1  3  5  7]
#  [19 21 23 25]
#  [37 39 41 43]
#  [55 57 59 61]
#  [73 75 77 79]]

[[ 1  3  5  7]
 [19 21 23 25]
 [37 39 41 43]
 [55 57 59 61]
 [73 75 77 79]]


#### Exercício 5: Somando Valor a Uma Submatriz (Nível Pro)

Dada a matriz abaixo (preenchida com zeros) adicione o valor 5 apenas ao bloco central 2x2.

In [ ]:
# Cria a matriz
matriz = np.zeros((4, 4), dtype = int)

In [24]:
# Solução
# Cria a matriz
matriz = np.zeros((4, 4), dtype = int)
matriz[1:3, 1:3] += 5
print(matriz)



# Saída esperada:
# [[0 0 0 0]
#  [0 5 5 0]
#  [0 5 5 0]
#  [0 0 0 0]]

[[0 0 0 0]
 [0 5 5 0]
 [0 5 5 0]
 [0 0 0 0]]


#### Exercício 6: Normalização de Uma Matriz (Nível Master)

Normalize a matriz abaixo. 

A normalização (Z-score) é feita subtraindo a média de todos os elementos de cada elemento e, em seguida, dividindo pelo desvio padrão. 

Fórmula: (X - media) / desvio_padrao.

In [ ]:
# Cria a matriz
matriz = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])

In [ ]:
# Solução
matriz = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
min_val = np.min(matriz)
max_val = np.max(matriz)

matriz_norm = (matriz - min_val) / (max_val - min_val)

print(matriz_norm)

[[0.    0.125 0.25 ]
 [0.375 0.5   0.625]
 [0.75  0.875 1.   ]]


#### Exercício 7: Substituindo Valores com Base em Uma Condição (Nível Ninja)

Dada a matriz abaixo, crie uma nova matriz onde todos os números maiores que 8 sejam substituídos pelo valor -1. Crie uma cópia da matriz antes de fazer a operação.

In [ ]:
# Cria a matriz
dados = np.arange(16).reshape(4, 4)

In [ ]:
# Solução
dados = np.arange(16).reshape(4, 4)
novos_dados = dados.copy()

novos_dados[dados > 8] = -1
print(novos_dados)

# Saída esperada:
# [[ 0  1  2  3]
#  [ 4  5  6  7]
#  [ 8 -1 -1 -1]
#  [-1 -1 -1 -1]]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8 -1 -1 -1]
 [-1 -1 -1 -1]]


#### Exercício 8: Inversa de Uma Matriz (Nível Ninja Pro Master)

Calcule a matriz inversa da matriz A. Depois, verifique seu trabalho calculando o produto de A pela sua inversa (o resultado deve ser a matriz identidade).

A matriz inversa de uma matriz quadrada A é outra matriz, chamada A⁻¹, que quando multiplicada por A resulta na matriz identidade (uma matriz que tem 1 na diagonal principal e 0 nos outros elementos). Em outras palavras, A × A⁻¹ = I. A inversa só existe para matrizes quadradas que não sejam singulares, ou seja, que tenham determinante diferente de zero. Ela é usada para resolver sistemas lineares, desfazer transformações e em várias aplicações de álgebra linear.

O determinante é um número único calculado a partir dos elementos de uma matriz quadrada (mesmo número de linhas e colunas) que resume algumas propriedades fundamentais da matriz. Ele indica, por exemplo, se a matriz é invertível (determinante diferente de zero) ou singular (determinante igual a zero).

In [ ]:
# Cria a matriz
A = np.array([[4, 7], [2, 6]])

In [ ]:
# Solução
A = np.array([[4, 7], [2, 6]])

determinante = np.linalg.det(A)

print(f"Determinante de A: {determinante:.2f}")

if determinante != 0:
  A_inversa = np.linalg.inv(A)
  print("Matriz Inversa: {A_inversa}")
else:
  print("A matriz é singular e não possui inversa.")

identidade = A @ A_inversa

print("\nResultado de A @ A_Inversa:")
print(np.round(identidade, decimals=2))


Determinante de A: 10.00
Matriz Inversa: {A_inversa}

Resultado de A @ A_Inversa:
[[1. 0.]
 [0. 1.]]


#### Exercício 9: Resolvendo Um Sistema de Equações Lineares (Nível Ninja Pro Master das Galáxias)
<!-- Trabalho Desenvolvido na Data Science Academy - www.datascienceacademy.com.br -->
Resolva o seguinte sistema de equações lineares:

2x + y = 8

x + 3y = 7

Represente o sistema na forma matricial Ax = b e encontre o vetor x (que contém os valores de x e y).

In [ ]:
# Solução
matriz = np.array([[2, 1],
                     [1, 3]])

vetor = np.array([8, 7])

solucao_x = np.linalg.solve(matriz, vetor)
solucao_arr = np.round(solucao_x, decimals=1)

## print(f"Resultado: x = {solucao_x[0]}, y = {solucao_x[1]}")
print(f"Resultado: {solucao_arr}")

# Saída esperada: [3.4 1.2]

Resultado: x = 3.4, y = 1.2000000000000002
Resultado: [3.4 1.2]


#### Exercício 10: Extraindo a Borda de Uma Matriz (Nível Ninja Pro Master das Galáxias Plus)

Dada uma matriz 5x5, crie um novo array 1D contendo todos os elementos da borda da matriz, em sentido horário, começando pelo canto superior esquerdo.

In [ ]:
# Cria a matriz
matriz = np.arange(25).reshape(5, 5)

In [35]:
# Solução
matriz = np.arange(25).reshape(5, 5)

topo = matriz[0, :-1]
direita = matriz[:-1, -1]
base = matriz[-1, ::-1][:-1]
esquerda = matriz[::-1, 0][:-1]

horario = np.concatenate([topo, direita, base, esquerda])
print(horario)


# Saída esperada: [ 0  1  2  3  4  9 14 19 24 23 22 21 20 15 10  5]

[ 0  1  2  3  4  9 14 19 24 23 22 21 20 15 10  5]


# Fim